default_stages: [commit]
default_language_version:
    python: python3.11

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: mixed-line-ending
# Spell Checker
-   repo: https://github.com/crate-ci/typos
    rev: v1.17.1
    hooks:
    -   id: typos
        args: []
# Git commit linter
-   repo: https://github.com/jorisroovers/gitlint
    rev:  v0.19.1
    hooks:
    -   id: gitlint
# Detect hardcoded secrets
-   repo: https://github.com/zricethezav/gitleaks
    rev: v8.18.1
    hooks:
      - id: gitleaks
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.12.1
    hooks:
      - id: black
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.13
    hooks:
      - id: ruff
# Check if pre-commit hooks version is equal to poetry.lock versions (not vise-versa)
-   repo: https://github.com/floatingpurr/sync_with_poetry
    rev: 1.1.0
    hooks:
      - id: sync_with_poetry
        args: ["--db", "sync_with_poetry_config.json"]
-   repo: https://github.com/python-poetry/poetry
    rev: 1.7.0
    hooks:
    -   id: poetry-export

ci:
  skip: [sync_with_poetry, poetry-export]
