line-length = 120
respect-gitignore = true
select = ["ALL"]
src = ["src"]
ignore = [
    # Disable flake8-commas
    "COM",
    # no-blank-line-before-class
    "D211",
    # multi-line-summary-second-line
    "D213",
    # Missing author in TODO
    "TD002",
    # Missing issue link on the line following this TODO
    "TD003",
]
